### ISSUE TITLE
Question about EFI files for similar build

### ISSUE THREAD

**Issue by alch3mistdev** [ruibeard/OpenCore-ASRock-Z490M-ITX-ac#1]
Hi Rui,

I've pretty inexperienced with opencore.

I have:
asrock-z490M-ITX-ac
Intel 10700 (non-k)
64gb 3200
RX580
Wifi/BT - onboard/orig

Just curious if you've had any further revelations with your setup, and from what you know, can i just go straight with your files?

- I don't need wifi/bt as I have gb lan in my flat (did the onboard wifi/bt work though?)
- as for the USB mappings, there are no headers but do all the rear ports work?

Any thoughts or help would be much appreciated. Really glad I found your repo. Cheers!

**Comment by ruibeard** [comment]
Hi man, sorry for late reply, I had the notifications off for issues. 

The bt wifi worked, but i was advised to use proper wifi/bt card from apple for better compatibility and stability on the bt side. The included in the motherboard should work fine with the instructions here  https://dortania.github.io/OpenCore-Install-Guide/ktext.html#wifi-and-bluetooth

For the usb, you can use my kext OR use the usbinjectall.kext and later with the usbmaptool do the proper mapping.
As far as I understood there's a limit to 15 ports. And USB3 ports count as 2 because they are usb2 and usb3 in the same connector. 
If you use my kext all the front ports are disabled but you can change that with the usbmaptool(to create a new kext). An option would be disabling the usb2 ports on the blue usb3 connector, to free up some for the front panel. 

As you are using an dGPU you have to check the opencore guide to check if you need anything else other than WhateverGreen. (i'm only using iGPU, it was just settings in the plist)

There is another repo that has other information that can be usefull for you. https://github.com/Old-Black-Dog/Hackintosh-ASRock-Z490M-ITX-ac

Anyway, if I can help with something else, let me know. Cheers!

**Comment by ruibeard** [comment]
Closed for now
